language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t rippili/docker-complex -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rippili/docker-complex npm test

after_success:
  - docker build -t rippili/multi-client ./client
  - docker build -t rippili/multi-nginx ./nginx
  - docker build -t rippili/multi-server ./server
  - docker build -t rippili/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rippili/multi-client
  - docker push rippili/multi-nginx
  - docker push rippili/multi-server
  - docker push rippili/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-424050176919"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  
  skip_cleanup: true